### PR TITLE
Assume nitrokey 0.4 compatible interface

### PR DESCRIPTION
**Pull request by robinkrahl**
Nitrokey 0.4 provides a major revamp of the public APIs. One of those
changes is the introduction of a Manager object that ensures that only a
single device connection can exist at any point in time (a constraint
ultimately imposed by libnitrokey).
This change adjusts the crate to be compatible with nitrokey 0.4.

----

Could you please release this as a new version (maybe 0.3.0-alpha.0?).  I’d
like to publish a new nitrokey-rs alpha with the connection manager changes,
and that requires an updated nitrokey-test version.

### CODE REVIEW

**Comment by robinkrahl** [comment]
Please ignore this pull request for the moment; I have to check something …  (It appears my plan to circumvent the lifetime problem by using `'static` for the manager did not work out.)

**Comment by robinkrahl** [comment]
As you found a fix for the lifetime issue in nitrocli, could you please go ahead with this change so that I can release a nitrokey-rs alpha version that includes the Manager refactoring?  Thanks!

**Comment by d-e-s-o** [comment]
Merged!

**Comment by d-e-s-o** [comment]
Hm, this cyclic dependency thing we got going is a real PITA. I can't even release a new version to `crates.io` that depends on `nitrokey-0.4`, simply because it always checks for existence of the same. Not sure if that's a bug in cargo's `--no-verify` option or what.

**Pull request closed without merging**
